---
- hosts: all

  become: true
  tasks:
    - name: ssh into container
      command: lxc-attach -n 102
      
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
