---
- hosts: all

  become: true
  tasks:
    - name: ssh into sonarr container
      ansible.builtin.shell: lxc-attach -n 102
    - name: update apt packages
      apt:
        upgrade: no
        update_cache: yes
