---
- hosts: all

  become: true
  tasks:
    - name: ssh into sonarr container
      shell: lxc-attach -n 102 && apt update && apt upgrade -y
    #- name: update apt packages
      #apt:
        #upgrade: no
        #update_cache: yes
